FROM mcr.microsoft.com/dotnet/aspnet:6.0 as base 
WORKDIR /app
EXPOSE 80
EXPOSE 443
FROM mcr.microsoft.com/dotnet/sdk:6.0 as build 
WORKDIR /src 
# COPY ["Services/Customer/Customer.API/Customer.API.csproj" , "Services/Customer/Customer.API/Customer.API.csproj"] 
# COPY ["BuildingBlocks/Common.Logging/Common.Logging.csproj" ,"BuildingBlocks/Common.Logging/Common.Logging.csproj" ]
# COPY ["BuildingBlocks/Contracts/Contracts.csproj" ,"BuildingBlocks/Contracts/Contracts.csproj" ]
# COPY ["BuildingBlocks/Infrastructure/Infrastructure.csproj" ,"BuildingBlocks/Infrastructure/Infrastructure.csproj" ]
# COPY ["BuildingBlocks/Shared/Shared.csproj" ,"BuildingBlocks/Shared/Shared.csproj" ]
# RUN dotnet restore Services/Customer/Customer.API/Customer.API.csproj
COPY . .
WORKDIR Services/Customer/Customer.API 
RUN dotnet build "Customer.API.csproj" -c Realease -o /app/build
RUN dotnet publish "Customer.API.csproj" -c Release -o /app/publish

FROM base 
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT [ "dotnet" , "Customer.API.dll" ]