FROM mcr.microsoft.com/dotnet/aspnet:6.0 as base 
WORKDIR /app
EXPOSE 80
EXPOSE 443 

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /src 
COPY ["/Services/Product/Product.API/Product.API.csproj" ,"/Services/Product/Product.API/"]
COPY ["/BuildingBlocks/Common.Logging/Common.Logging.csproj" ,"/BuildingBlocks/Common.Logging/"]
COPY ["/BuildingBlocks/Infrastructure/Infrastructure.csproj" ,"/BuildingBlocks/Infrastructure/"]
COPY ["/BuildingBlocks/Shared/Shared.csproj" ,"/BuildingBlocks/Shared/"]
COPY ["/BuildingBlocks/Contracts/Contracts.csproj" ,"/BuildingBlocks/Contracts/"]
RUN dotnet restore "/Services/Product/Product.API/Product.API.csproj" 
COPY . .
WORKDIR /src/Services/Product/Product.API
RUN dotnet build Product.API.csproj -c Release -o /app/build

RUN dotnet publish "Product.API.csproj" -c Release -o /app/publish

FROM base
WORKDIR /app
COPY --from=build /app/publish . 
ENTRYPOINT [ "dotnet" , "Product.API.dll"] 